<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Шины");
?>

<?$APPLICATION->IncludeComponent(
	"bitrix:catalog", 
	"tyres", 
	array(
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "4",
		"BASKET_URL" => "/personal/cart/",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SEF_MODE" => "Y",
		"SEF_FOLDER" => "/tyres/",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_SHADOW" => "Y",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600",
		"CACHE_FILTER" => "N",
		"DISPLAY_PANEL" => "Y",
		"SET_TITLE" => "Y",
		"SET_STATUS_404" => "Y",
		"USE_FILTER" => "Y",
		"FILTER_NAME" => "arrFilter",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PRICE_CODE" => array(
			0 => "Продажи через сайт",
		),
		"USE_REVIEW" => "N",
		"USE_COMPARE" => "N",
		"COMPARE_NAME" => "CATALOG_COMPARE_LIST",
		"COMPARE_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"COMPARE_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"DISPLAY_ELEMENT_SELECT_BOX" => "N",
		"ELEMENT_SORT_FIELD_BOX" => "name",
		"ELEMENT_SORT_ORDER_BOX" => "asc",
		"COMPARE_ELEMENT_SORT_FIELD" => "sort",
		"COMPARE_ELEMENT_SORT_ORDER" => "asc",
		"PRICE_CODE" => array(
			0 => "Продажи через сайт",
		),
		"USE_PRICE_COUNT" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"SHOW_TOP_ELEMENTS" => "Y",
		"TOP_ELEMENT_COUNT" => "9",
		"TOP_LINE_ELEMENT_COUNT" => "3",
		"TOP_ELEMENT_SORT_FIELD" => "name",
		"TOP_ELEMENT_SORT_ORDER" => "desc",
		"TOP_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"PAGE_ELEMENT_COUNT" => "100",
		"LINE_ELEMENT_COUNT" => strpos(SITE_TEMPLATE_ID,"one")!==false?5:4,
		"ELEMENT_SORT_FIELD" => "name",
		"ELEMENT_SORT_ORDER" => "asc",
		"LIST_PROPERTY_CODE" => array(
			0 => "model_season",
			1 => "",
		),
		"INCLUDE_SUBSECTIONS" => "Y",
		"LIST_META_KEYWORDS" => "UF_META_KEYWORDS",
		"LIST_META_DESCRIPTION" => "UF_META_DESCRIPTION",
		"LIST_BROWSER_TITLE" => "UF_BROWSER_TITLE",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "SEZON",
			1 => "model_season",
			2 => "SHIP_NE_SHIP",
			3 => "TIP",
			4 => "model_pin",
			5 => "BREND",
			6 => "model_type",
			7 => "CML2_ARTICLE",
			8 => "CML2_BASE_UNIT",
			9 => "DOPINFO",
			10 => "CML2_MANUFACTURER",
			11 => "CML2_TRAITS",
			12 => "CML2_TAXES",
			13 => "CML2_ATTRIBUTES",
			14 => "CML2_BAR_CODE",
			15 => "BRENDDISKI",
			16 => "MODELDISKI",
			17 => "description",
			18 => "TIPDISKI",
			19 => "MODEL",
			20 => "BREND_1",
			21 => "KOL_VO_OTVERSTIY",
			22 => "TSVET",
			23 => "DOP_SVEDENIE",
			24 => "ARTIKUL",
			25 => "model_more_photos",
			26 => "",
		),
		"DETAIL_META_KEYWORDS" => "-",
		"DETAIL_META_DESCRIPTION" => "description",
		"DETAIL_BROWSER_TITLE" => "-",
		"LINK_IBLOCK_TYPE" => "",
		"LINK_IBLOCK_ID" => "",
		"LINK_PROPERTY_SID" => "",
		"LINK_ELEMENTS_URL" => "",
		"USE_ALSO_BUY" => "Y",
		"ALSO_BUY_ELEMENT_COUNT" => "5",
		"ALSO_BUY_MIN_BUYES" => "2",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Товары",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"ADD_SECTIONS_CHAIN" => "Y",
		"OFFERS_CART_PROPERTIES" => array(
			0 => "tyre_width",
			1 => "tyre_height",
			2 => "tyre_diameter",
			3 => "tyre_on_index",
			4 => "hit",
			5 => "TIP",
			6 => "BREND",
			7 => "SEZON",
			8 => "CML2_ARTICLE",
			9 => "CML2_BASE_UNIT",
			10 => "tyre_load",
			11 => "order",
			12 => "CML2_MANUFACTURER",
			13 => "CML2_TRAITS",
			14 => "CML2_TAXES",
			15 => "CML2_ATTRIBUTES",
			16 => "SHIP_NE_SHIP",
			17 => "CML2_BAR_CODE",
			18 => "BRENDDISKI",
			19 => "tyre_speed",
			20 => "DOPINFO",
			21 => "DIAMETRDISKI",
			22 => "title",
			23 => "keywords",
			24 => "description",
			25 => "TIPDISKI",
			26 => "SHIRINADISKI",
			27 => "MODEL_1",
			28 => "INDEKS_NAGRUZKI_I_SKOROSTI",
			29 => "INDEKS_SKOROSTI",
			30 => "BREND_1",
			31 => "TIP_1",
			32 => "KOL_VO_OTVERSTIY",
			33 => "PCD",
			34 => "VYLET_ET",
			35 => "DIA",
			36 => "TSVET",
			37 => "DOP_SVEDENIE",
			38 => "ARTIKUL",
		),
		"LIST_OFFERS_FIELD_CODE" => array(
			0 => "NAME",
			1 => "",
		),
		"DETAIL_OFFERS_FIELD_CODE" => array(
			0 => "NAME",
			1 => "CATALOG_QUANTITY",
			2 => "",
		),
		"COMPONENT_TEMPLATE" => "tyres",
		"HIDE_NOT_AVAILABLE" => "N",
		"CACHE_GROUPS" => "Y",
		"ADD_ELEMENT_CHAIN" => "N",
		"USE_ELEMENT_COUNTER" => "Y",
		"FILTER_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"CONVERT_CURRENCY" => "Y",
		"USE_PRODUCT_QUANTITY" => "Y",
		"PRODUCT_QUANTITY_VARIABLE" => "",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRODUCT_PROPERTIES" => array(
			0 => "SEZON",
			1 => "model_season",
			2 => "SHIP_NE_SHIP",
			3 => "TIP",
			4 => "model_pin",
			5 => "model_type",
			6 => "DOPINFO",
			7 => "CML2_MANUFACTURER",
			8 => "CML2_TRAITS",
			9 => "CML2_TAXES",
			10 => "CML2_ATTRIBUTES",
			11 => "MODELDISKI",
			12 => "TIPDISKI",
			13 => "MODEL",
			14 => "KOL_VO_OTVERSTIY",
			15 => "DOP_SVEDENIE",
			16 => "ARTIKUL",
		),
		"TOP_ELEMENT_SORT_FIELD2" => "id",
		"TOP_ELEMENT_SORT_ORDER2" => "desc",
		"TOP_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"TOP_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"TOP_OFFERS_LIMIT" => "5",
		"SECTION_COUNT_ELEMENTS" => "Y",
		"SECTION_TOP_DEPTH" => "2",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER2" => "desc",
		"LIST_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_OFFERS_LIMIT" => "5",
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
		"SHOW_DEACTIVATED" => "N",
		"DETAIL_OFFERS_PROPERTY_CODE" => array(
			0 => "tyre_width",
			1 => "tyre_height",
			2 => "tyre_diameter",
			3 => "tyre_on_index",
			4 => "hit",
			5 => "TIP",
			6 => "BREND",
			7 => "SEZON",
			8 => "CML2_ARTICLE",
			9 => "CML2_BASE_UNIT",
			10 => "tyre_load",
			11 => "MORE_PHOTO",
			12 => "order",
			13 => "CML2_MANUFACTURER",
			14 => "CML2_TRAITS",
			15 => "CML2_TAXES",
			16 => "FILES",
			17 => "CML2_ATTRIBUTES",
			18 => "SHIP_NE_SHIP",
			19 => "CML2_BAR_CODE",
			20 => "BRENDDISKI",
			21 => "tyre_speed",
			22 => "DOPINFO",
			23 => "DIAMETRDISKI",
			24 => "title",
			25 => "keywords",
			26 => "description",
			27 => "TIPDISKI",
			28 => "SHIRINADISKI",
			29 => "MODEL_1",
			30 => "INDEKS_NAGRUZKI_I_SKOROSTI",
			31 => "INDEKS_SKOROSTI",
			32 => "BREND_1",
			33 => "TIP_1",
			34 => "KOL_VO_OTVERSTIY",
			35 => "PCD",
			36 => "VYLET_ET",
			37 => "DIA",
			38 => "TSVET",
			39 => "DOP_SVEDENIE",
			40 => "ARTIKUL",
			41 => "MODELDISKI",
			42 => "SHIPOVANNYE",
			43 => "SEZON_1",
			44 => "",
		),
		"USE_STORE" => "N",
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER2" => "desc",
		"CURRENCY_ID" => "RUB",
		"SEF_URL_TEMPLATES" => array(
			"sections" => "",
			"section" => "#SECTION_CODE#/",
			"element" => "#SECTION_CODE#/#ELEMENT_CODE#/",
			"compare" => "compare.php?action=#ACTION_CODE#",
		),
		"VARIABLE_ALIASES" => array(
			"compare" => array(
				"ACTION_CODE" => "action",
			),
		)
	),
	false
);?>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>
